# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_university_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='specialty',
        ),
    ]
