# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_university_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
