# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20180517_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='representative',
        ),
    ]
