# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_auto_20180517_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
