# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_xxxs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Xxxs',
        ),
    ]
