# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Entrant'), (3, 'Other')], default=1),
        ),
    ]
